#服务配置
server:
  port: 8892
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  context-path: /user

#数据库配置
spring:
  datasource:
    url : jdbc:mysql://192.168.1.244:3306/hm_user
    username : '{cipher}bef237d2016012404448bc8d3656f9b146c116188b7d5667b622bf95aefd7a5d'
    password : abc-123
    driverClassName : com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  application:
    name: provider-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://wyc:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: hello-world

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cloud.provider.entity
